# Generated by Django 5.1.4 on 2024-12-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoundItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=255)),
                ('date_found', models.DateField()),
                ('details', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('finder_email', models.EmailField(max_length=254)),
                ('finder_password', models.CharField(max_length=128)),
                ('image', models.ImageField(blank=True, null=True, upload_to='found_items/')),
            ],
        ),
    ]
